// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "home24-page-analyser/model"

	mock "github.com/stretchr/testify/mock"
)

// AnalyserService is an autogenerated mock type for the AnalyserService type
type AnalyserService struct {
	mock.Mock
}

// Analyse provides a mock function with given fields: request
func (_m *AnalyserService) Analyse(request model.PageAnalyseRequest) (model.PageAnalysisResponse, error) {
	ret := _m.Called(request)

	var r0 model.PageAnalysisResponse
	if rf, ok := ret.Get(0).(func(model.PageAnalyseRequest) model.PageAnalysisResponse); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(model.PageAnalysisResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.PageAnalyseRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
