// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "home24-page-analyser/model"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Parser is an autogenerated mock type for the Parser type
type Parser struct {
	mock.Mock
}

// Parse provides a mock function with given fields: reader, domain
func (_m *Parser) Parse(reader io.Reader, domain string) (model.PageAnalysisResponse, error) {
	ret := _m.Called(reader, domain)

	var r0 model.PageAnalysisResponse
	if rf, ok := ret.Get(0).(func(io.Reader, string) model.PageAnalysisResponse); ok {
		r0 = rf(reader, domain)
	} else {
		r0 = ret.Get(0).(model.PageAnalysisResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(io.Reader, string) error); ok {
		r1 = rf(reader, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
